name: Daily Sync Upstream

on:
  schedule:
    - cron: '0 1 * * *' # 每天UTC 1点自动执行
  workflow_dispatch:    # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Add upstream remote
        run: git remote add upstream https://github.com/LibreTV/LibreTV.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Rebase onto upstream/main
        run: git rebase upstream/main

      - name: Push changes to forked repo
        run: |
          git push origin HEAD:main --force
        env:
          # 这可以让 GitHub Actions 自动推送到你的仓库
          # GitHub 会自动处理 GITHUB_TOKEN，无需手动设置
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}